version: '3.8'

services:
  eureka-server:
    build: 
      context: ./eureka-server
      dockerfile: Dockerfile
    image: skillfactory/eureka-server
    ports:
      - "8761:8761"
    networks:
      - skillfactory-net
    healthcheck:
        test: ["CMD", "wget", "-q", "--spider", "http://localhost:8761/actuator/health"]
        interval: 10s
        timeout: 5s
        retries: 5

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    image: skillfactory/api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
    networks:
      - skillfactory-net
    depends_on:
      - eureka-server

  hotel-service:
    build: 
      context: ./hotel-service
      dockerfile: Dockerfile
    image: skillfactory/hotel-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8082
    networks:
      - skillfactory-net
    depends_on:
      - eureka-server

  booking-service:
    build: 
      context: ./booking-service
      dockerfile: Dockerfile
    image: skillfactory/booking-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8081
    networks:
      - skillfactory-net
    depends_on:
      - eureka-server

networks:
  skillfactory-net:
    driver: bridge
